name: Upload Mod to NexusMods

on:
    release:
        types: [published]
    workflow_dispatch: 
        inputs: 
            version:
                description: 'Version number for the release'
                required: true
                
jobs:
    upload-to-nexusmods:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6
              
            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 9.0.x
            
            - name: Publish Mod
              run: dotnet publish -c Release
              
            - name: Zip dist
              run: cd dist && zip -r ../TheVoidSts2Mod.zip TheVoid
              
            - name: Upload mod to NexusMods
              id: upload
              uses: Nexus-Mods/upload-action@main
              with:
                  api_key: ${{ secrets.NEXUSMODS_API_KEY }}
                  file_group_id: ${{ vars.NEXUSMODS_FILE_GROUP_ID }}
                  filename: TheVoidSts2Mod.zip
                  display_name: "The Void - Sloddervos66"
                  description: ${{ github.event.release.body }}
                  version: ${{ github.event.release.tag_name || github.event.inputs.version }}